const monsters = {
  monster1: {
    "name": "Slime",
    "health": 200,
    "strength": 4,
    "mental": 3,
    "default_attack": "strength",
    "nuts": [30,90],
    "exp": [15,30],
    "distance": [0,10],
    "probability": 90,
    "victory_msg": "Tintintintinnn Tintintintintiiiiiiiiiiiiiiin !",
    "defeat_msg": "So sick to lose against a so weak creature."
  },
  monster2: {
    "name": "Big Weird Tentacles Sticking Out Of The Ground", 
    "health": 250,
    "strength": 4,
    "mental": 4,
    "default_attack": "all",
    "nuts": [50,110],
    "exp": [25,40],
    "distance": [0,19],
    "probability": 80,
    "victory_msg": "Congratulations !",
    "defeat_msg": "So sick to lose against a so weak creature."
  },
  monster3: {
    "name": "Angry Bird With Big Horn", 
    "health": 320,
    "strength": 5,
    "mental": 3,
    "default_attack": "strength",
    "nuts": [40,100],
    "exp": [20,35],
    "distance": [5,19],
    "probability": 60,
    "victory_msg": "Few, it was so angry ! It was heading straight on you like you were a castle.",
    "defeat_msg": "A rain of these creatures were thrown on you. Weird."
  },
  monster4: {
    "name": "Nasty Martian",
    "health": 700,
    "strength": 8,
    "mental": 6,
    "default_attack": "strength",
    "nuts": [100,220],
    "exp": [70,140],
    "distance": [20,39],
    "probability": 40,
    "victory_msg": "It was so nasty !",
    "defeat_msg": "The Martian danced on your corpse when you died."
  },
  monster5: {
    "name": "Big Slime",
    "health": 800,
    "strength": 10,
    "mental": 10,
    "default_attack": "strength",
    "nuts": [90,250],
    "exp": [80,170],
    "distance": [20,39],
    "probability": 60,
    "victory_msg": "Oh my god, I've never seen a slime like that before!",
    "defeat_msg": "It said it was angry because we killed its children."
  },
  monster6: {
    "name": "Ugly Glue",
    "health": 2000,
    "strength": 3,
    "mental": 3,
    "default_attack": "strength",
    "nuts": [1,1],
    "exp": [1,1],
    "distance": [0,100],
    "probability": 5,
    "victory_msg": "Hmmm.... I think we lost times fighting this... thing.",
    "defeat_msg": "The moment it shoves on our eyes, it blinds you, and then, you fall into a big hole and die on the return."
  },
  monster7: {
    "name": "Little Martian With Big Red Eyes",
    "health": 150,
    "strength": 30,
    "mental": 1,
    "default_attack": "strength",
    "nuts": [80,140],
    "exp": [80,150],
    "distance": [20,39],
    "probability": 25,
    "victory_msg": "Ouaw ! This monster was so scary !",
    "defeat_msg": "When it threw its laser from its antenna, you were electrilized like a tazer. Finito."
  },
  monster7: {
    "name": "Little Martian With Big Red Eyes",
    "health": 150,
    "strength": 30,
    "mental": 1,
    "default_attack": "strength",
    "nuts": [80,140],
    "exp": [80,150],
    "distance": [20,39],
    "probability": 25,
    "victory_msg": "Ouaw ! This monster was so scary !",
    "defeat_msg": "When it threw its laser from its antenna, you were electrilized like a tazer. Finito."
  },
  monster13: {
    "name": "Little Cute Chipmunk With Big Eyes But Horrible Scary Smile With Large, Sharp Teeth",
    "health": 5000,
    "strength": 5,
    "mental": 12,
    "default_attack": "mental",
    "nuts": [200,300],
    "exp": [130,220],
    "distance": [20,39],
    "probability": 30,
    "victory_msg": "This smile gave me goose humps.",
    "defeat_msg": "Its mouth became giant and swallowed you whole."
  },
  monster9: {
    "name": "Enraged Werewolf",
    "health": 1600,
    "strength": 22,
    "mental": 15,
    "default_attack": "strength",
    "nuts": [300,500],
    "exp": [300,500],
    "distance": [40,59],
    "probability": 20,
    "victory_msg": "Urk! So much drool was dripping out from that's wolf mouth !",
    "defeat_msg": "When the Werewolf bites you, you tried to flee but you finish into a big shaking and big pain. And then, you died. So sick."
  },
  monster13: {
    "name": "A Lava-Spitting Teapot",
    "health": 2500,
    "strength": 10,
    "mental": 20,
    "default_attack": "mental",
    "nuts": [350,550],
    "exp": [250,600],
    "distance": [40,59],
    "probability": 30,
    "victory_msg": "Wow ! This was the most epic fight I've ever did !",
    "defeat_msg": "Hmm... Lose against a teapot..."
  },
  monster10: {
    "name": "Big Button Nose Sorcerer With Piercing Laugh",
    "health": 2200,
    "strength": 10,
    "mental": 24,
    "default_attack": "mental",
    "nuts": [500,800],
    "exp": [300,500],
    "distance": [40,79],
    "probability": 10,
    "victory_msg": "You won the moment you pierced the button on that sorcerer's nose.",
    "defeat_msg": "It turned you into a stuffed pig and hung your new form on a wall of its house."
  },
  monster11: {
    "name": "Dark Starship Trooper With Laser Gun",
    "health": 3500,
    "strength": 16,
    "mental": 30,
    "default_attack": "mental",
    "nuts": [2500,4800],
    "exp": [550,820],
    "distance": [60,79],
    "probability": 50,
    "victory_msg": "I thinked the troopers was in mission on another planet. But it didn't.",
    "defeat_msg": "Damn! The laser he throws just desintegrated you in dust in half of a second for breath."
  },
  monster14: {
    "name": "Humanoid Shark With Hawaiian Shirt And Steel Harpoon",
    "health": 4200,
    "strength": 30,
    "mental": 30,
    "default_attack": "all",
    "nuts": [2200,4600],
    "exp": [600,900],
    "distance": [60,79],
    "probability": 50,
    "victory_msg": "OMG ! It tries to fishing you !",
    "defeat_msg": "It threw it's harpoon and caught you like a common fish."
  },
  monster15: {
    "name": "iPhone 14 Pro Max",
    "health": 7500,
    "strength": 35,
    "mental": 35,
    "default_attack": "all",
    "nuts": [7000,10000],
    "exp": [1000,1500],
    "distance": [80,100],
    "probability": 25,
    "victory_msg": "That was so ",
    "defeat_msg": "It threw it's harpoon and caught you like a common fish."
  },
  monster12: {
    "name": "Weird Red Cactus With Human Arms",
    "health": 100,
    "strength": 1,
    "mental": 1,
    "default_attack": "mental",
    "nuts": [1000,1000],
    "exp": [1000,1000],
    "distance": [0,100],
    "probability": 1,
    "victory_msg": "Oh! So Lucky !",
    "defeat_msg": "W... What ??? I didn't think that was possible."
  }
}

export default monsters;